# Generated by Django 4.0.5 on 2022-06-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=12, verbose_name='Identificador')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('profesor', models.TextField(verbose_name='Profesor')),
                ('horario', models.TextField(max_length=10, verbose_name='Horario')),
                ('numAlumnos', models.SmallIntegerField(verbose_name='Alumnos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
