# Generated by Django 4.0.5 on 2022-06-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo', '0002_cursos_delete_alumnos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
