# Generated by Django 4.0.5 on 2022-08-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo', '0005_actividadadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadAdmin',
            new_name='ActividadContacto',
        ),
    ]
